# Практическая работа 1-1 Numpy

1. Скачайте этот ноутбук к себе.
2. Заполните пропущенные ячейки, отвечая на заданные вопросы. Там должен быть код! (если не сказано обратное)
3. Сохраните результат в своём гитхаб репозитории.

#### Полезная литература

- http://www.numpy.org/
- https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html
- https://docs.scipy.org/doc/numpy/user/quickstart.html

1) Импортировать numpy и написать версию

In [1]:
import numpy as np

print("Версия NumPy:", np.__version__)

Версия NumPy: 1.21.4


2) Создать нулевой вектор размера 10

In [2]:
zero_vector = np.zeros(10)
zero_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3) Создать вектор заполненный 7-ами размера 7

In [3]:
seven_vector = np.full(7, 7)
seven_vector

array([7, 7, 7, 7, 7, 7, 7])

4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
even_vector = np.arange(10, 101, 2)
even_vector

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
random_array = np.random.random(5)
print("Исходный массив:")
print(random_array)

reversed_array = np.flip(random_array)
print("\nМассив задом наперёд:")
print(reversed_array)

Исходный массив:
[0.37933167 0.71070786 0.55693535 0.56348154 0.61415933]

Массив задом наперёд:
[0.61415933 0.56348154 0.55693535 0.71070786 0.37933167]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
matrix = np.arange(9).reshape((3, 3))
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
matrix = np.eye(4, k=1)
matrix

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
matrix = np.full((4, 4), 7)
np.fill_diagonal(matrix, [1, 2, 3, 4])
matrix

array([[1, 7, 7, 7],
       [7, 2, 7, 7],
       [7, 7, 3, 7],
       [7, 7, 7, 4]])

9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [9]:
matrix = np.tile(np.arange(5), (5, 1))
matrix

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [10]:
matrix1 = np.random.rand(10, 10)
matrix1_centered = matrix1 - matrix1.mean(axis=1, keepdims=True)
matrix1_centered

array([[ 0.3165727 , -0.01503306, -0.01939804,  0.09286524, -0.48353356,
        -0.06241674,  0.18611951, -0.32402137,  0.4178193 , -0.10897397],
       [-0.06073411, -0.37211624, -0.01413956, -0.13871214,  0.47196227,
        -0.19939323,  0.28053056,  0.10652656, -0.0173298 , -0.05659428],
       [-0.39343168, -0.18554049,  0.3003382 , -0.2256669 , -0.08209972,
         0.26989112,  0.35679819,  0.11126311,  0.17009523, -0.32164707],
       [ 0.10464033, -0.01834673,  0.25429546,  0.06276153,  0.00819075,
         0.19081258,  0.06238543, -0.27711825, -0.19425884, -0.19336227],
       [ 0.38882236,  0.54799789,  0.10012171, -0.266866  ,  0.05071304,
        -0.28956611, -0.3822699 , -0.32290032, -0.37652242,  0.55046974],
       [-0.05241013,  0.15201412, -0.31241833,  0.08808315,  0.28395933,
         0.28299311, -0.17779402, -0.32109207,  0.43815795, -0.38149311],
       [-0.12901989,  0.25648886, -0.44390592,  0.09308128, -0.45653289,
         0.49323313, -0.19004686, -0.09223501

11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [11]:
matrix2 = np.random.rand(10, 10)

matrix2_centered = matrix2 - np.median(matrix2, axis=0, keepdims=True)
matrix2_centered

array([[ 0.0078735 ,  0.36731579,  0.00592536,  0.48604782, -0.30163943,
         0.27159533, -0.08951269,  0.08779213, -0.37552515, -0.29640517],
       [-0.36366699,  0.49197971, -0.00592536, -0.35920333,  0.40670098,
         0.47225943, -0.07477687, -0.11362689,  0.30607623,  0.26690145],
       [ 0.44566634, -0.28371261, -0.4847233 ,  0.18585423,  0.46189666,
         0.18559758,  0.07477687, -0.09898518, -0.27672675,  0.09214464],
       [-0.43495535,  0.02289327,  0.1300203 , -0.44095131,  0.13218027,
        -0.16432592,  0.18490293,  0.34925947, -0.5432849 ,  0.09741979],
       [ 0.36054776,  0.44638049,  0.16681875,  0.04568287, -0.20170678,
         0.35076018,  0.23609577, -0.36000927,  0.00959349,  0.43117204],
       [-0.0078735 , -0.08064316,  0.34536537,  0.41727889, -0.15047426,
        -0.35820853, -0.2834939 , -0.37912738,  0.3723253 , -0.24516422],
       [ 0.09561395, -0.28388591, -0.29515675, -0.10144381, -0.13218027,
         0.02162931, -0.1079964 ,  0.19360225

12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [12]:
matrix3 = np.random.rand(5, 5)

matrix3_extended = np.column_stack([matrix3, matrix3.max(axis=1), matrix3.min(axis=1)])
matrix3_extended

array([[0.75075798, 0.36884447, 0.9317748 , 0.61600901, 0.64849384,
        0.9317748 , 0.36884447],
       [0.07704933, 0.07160035, 0.70061096, 0.60114565, 0.94134543,
        0.94134543, 0.07160035],
       [0.14311906, 0.39003609, 0.9239695 , 0.6111795 , 0.46188514,
        0.9239695 , 0.14311906],
       [0.83167764, 0.09823004, 0.31327813, 0.03624689, 0.58773763,
        0.83167764, 0.03624689],
       [0.98365429, 0.49048463, 0.03449264, 0.97458013, 0.34001025,
        0.98365429, 0.03449264]])

13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [15]:
vector = np.arange(1, 52)

odd_vector = vector[vector % 2 != 0]
even_vector = vector[vector % 2 == 0]

product_matrix = np.outer(odd_vector, even_vector)

pseudo_inverse_matrix = np.linalg.pinv(product_matrix)

print("\nПроизведение матриц:")
display(product_matrix)
print("\nОбратная матрица произведения:")
display(pseudo_inverse_matrix)


Произведение матриц:


array([[   2,    4,    6,    8,   10,   12,   14,   16,   18,   20,   22,
          24,   26,   28,   30,   32,   34,   36,   38,   40,   42,   44,
          46,   48,   50],
       [   6,   12,   18,   24,   30,   36,   42,   48,   54,   60,   66,
          72,   78,   84,   90,   96,  102,  108,  114,  120,  126,  132,
         138,  144,  150],
       [  10,   20,   30,   40,   50,   60,   70,   80,   90,  100,  110,
         120,  130,  140,  150,  160,  170,  180,  190,  200,  210,  220,
         230,  240,  250],
       [  14,   28,   42,   56,   70,   84,   98,  112,  126,  140,  154,
         168,  182,  196,  210,  224,  238,  252,  266,  280,  294,  308,
         322,  336,  350],
       [  18,   36,   54,   72,   90,  108,  126,  144,  162,  180,  198,
         216,  234,  252,  270,  288,  306,  324,  342,  360,  378,  396,
         414,  432,  450],
       [  22,   44,   66,   88,  110,  132,  154,  176,  198,  220,  242,
         264,  286,  308,  330,  352,  374,  396,  


Обратная матрица произведения:


array([[3.86313231e-09, 1.15893969e-08, 1.93156616e-08, 2.70419262e-08,
        3.47681908e-08, 4.24944554e-08, 5.02207201e-08, 5.79469847e-08,
        6.56732493e-08, 7.33995139e-08, 8.11257786e-08, 8.88520432e-08,
        9.65783078e-08, 1.04304572e-07, 1.12030837e-07, 1.19757102e-07,
        1.27483366e-07, 1.35209631e-07, 1.42935896e-07, 1.50662160e-07,
        1.58388425e-07, 1.66114689e-07, 1.73840954e-07, 1.81567219e-07,
        1.89293483e-07, 1.97019748e-07],
       [7.72626463e-09, 2.31787939e-08, 3.86313231e-08, 5.40838524e-08,
        6.95363816e-08, 8.49889109e-08, 1.00441440e-07, 1.15893969e-07,
        1.31346499e-07, 1.46799028e-07, 1.62251557e-07, 1.77704086e-07,
        1.93156616e-07, 2.08609145e-07, 2.24061674e-07, 2.39514203e-07,
        2.54966733e-07, 2.70419262e-07, 2.85871791e-07, 3.01324320e-07,
        3.16776850e-07, 3.32229379e-07, 3.47681908e-07, 3.63134437e-07,
        3.78586967e-07, 3.94039496e-07],
       [1.15893969e-08, 3.47681908e-08, 5.79469847e-08

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами. 

In [14]:
chessboard_matrix = np.zeros((8, 8), dtype=int)

chessboard_matrix[1::2, ::2] = 1
chessboard_matrix[::2, 1::2] = 1
chessboard_matrix

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])